apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: su-inntekt
   namespace: default
   labels:
      team: supstonad
spec:
   image: {{ image }}
   replicas:
      min: 1
   liveness:
      path: isalive
   readiness:
      path: isready
   webproxy: true
   vault:
      enabled: true
      paths:
         -  mountPath: /var/run/secrets/nais.io/vault
            kvPath: /secret/supstonad/{{ secret_env }}
         -  mountPath: /var/run/secrets/nais.io/vault/su-inntekt
            kvPath: /kv/{{ cluster }}/fss/su-inntekt/default
         -  mountPath: /var/run/secrets/nais.io/azuread
            kvPath: /azuread/data/{{ secret_env }}/creds/su-inntekt
